# Music Genre Classifier by using Lasso regression.



In [1]:
% run feature_extract.py

('idx is', 0)


/Users/yangxiao/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/linalg/linalg.py:2257: RuntimeWarning: invalid value encountered in sqrt
  ret = sqrt(sqnorm)


('idx is', 1)
('idx is', 2)
('idx is', 3)
('idx is', 4)
('idx is', 5)
('idx is', 6)
('idx is', 7)
('idx is', 8)
('idx is', 9)
('idx is', 10)
('idx is', 11)
('idx is', 12)
('idx is', 13)
('idx is', 14)
('idx is', 15)
('idx is', 16)
('idx is', 17)
('idx is', 18)
('idx is', 19)
('idx is', 20)
('idx is', 21)
('idx is', 22)
('idx is', 23)
('idx is', 24)
('idx is', 25)
('idx is', 26)
('idx is', 27)
('idx is', 28)
('idx is', 29)
('idx is', 30)
('idx is', 31)
('idx is', 32)
('idx is', 33)
('idx is', 34)
('idx is', 35)
('idx is', 36)
('idx is', 37)
('idx is', 38)
('idx is', 39)
('idx is', 40)
('idx is', 41)
('idx is', 42)
('idx is', 43)
('idx is', 44)
('idx is', 45)
('idx is', 46)
('idx is', 47)
('idx is', 48)
('idx is', 49)
('idx is', 50)
('idx is', 51)
('idx is', 52)
('idx is', 53)
('idx is', 54)
('idx is', 55)
('idx is', 56)
('idx is', 57)
('idx is', 58)
('idx is', 59)
('idx is', 60)
('idx is', 61)
('idx is', 62)
('idx is', 63)
('idx is', 64)
('idx is', 65)
('idx is', 66)
('idx is', 67)
('id

In [9]:
% run logistic.py

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [2]:
import numpy as np

Music_Genre=["classical","jazz","pop","rock"]

#load train and val data set
train_data=np.load("./feature_data/train/train_sample.npy")
train_label=np.load("./feature_data/train/train_label.npy")
val_data=np.load("./feature_data/val/val_sample.npy")
val_label=np.load("./feature_data/val/val_label.npy")

In [3]:
L = [0.1,1,10,13,15,17,21,30,100]


In [4]:
print("train_data.shape is",train_data.shape)
print("train_label.shape is",train_label.shape)

print("val_data.shape is",val_data.shape)
print("val_label.shape is",val_label.shape)

('train_data.shape is', (9600, 32))
('train_label.shape is', (9600,))
('val_data.shape is', (1200, 32))
('val_label.shape is', (1200,))


# Please implement Lasso_Regression_Classifier 

In [5]:
# Please implement Classifier in the file : Lasso_Regression_Classifier.py
from cs536_3.models import Lasso_Regression_Classifier

average_win=40 #Student will change this#

for l in L: 
    LRC = Lasso_Regression_Classifier(train_data.transpose(),l,train_label,average_win)
    val_pred=LRC.predict(val_data)
    print(val_pred)
    print(val_label)
    val_acc = np.sum(val_pred==val_label)/(1.0*(len(val_pred)))
    
    print("Regularization_L:".format(),"Validation Accuracy is".format(),l,val_acc)

(0, ' th sample')


/Users/yangxiao/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


(100, ' th sample')
(200, ' th sample')
(300, ' th sample')
(400, ' th sample')
(500, ' th sample')
(600, ' th sample')
(700, ' th sample')
(800, ' th sample')
(900, ' th sample')
(1000, ' th sample')
(1100, ' th sample')
[3. 3. 3. ... 0. 0. 0.]
[2. 2. 2. ... 0. 0. 0.]
('Regularization_L:', 'Validation Accuracy is', 0.1, 0.5)
(0, ' th sample')
(100, ' th sample')
(200, ' th sample')
(300, ' th sample')
(400, ' th sample')
(500, ' th sample')
(600, ' th sample')
(700, ' th sample')
(800, ' th sample')
(900, ' th sample')
(1000, ' th sample')
(1100, ' th sample')
[2. 2. 2. ... 0. 0. 0.]
[2. 2. 2. ... 0. 0. 0.]
('Regularization_L:', 'Validation Accuracy is', 1, 0.85)
(0, ' th sample')
(100, ' th sample')
(200, ' th sample')
(300, ' th sample')
(400, ' th sample')
(500, ' th sample')
(600, ' th sample')
(700, ' th sample')
(800, ' th sample')
(900, ' th sample')
(1000, ' th sample')
(1100, ' th sample')
[2. 2. 2. ... 0. 0. 0.]
[2. 2. 2. ... 0. 0. 0.]
('Regularization_L:', 'Validation Accur

KeyboardInterrupt: 

# Please select My L and check the test performance.

In [6]:
## Test data load
test_data=np.load("./feature_data/test/test_sample.npy")
test_label=np.load("./feature_data/test/test_label.npy")

In [7]:
My_L = 13  #student answer
LRC = Lasso_Regression_Classifier(train_data.transpose(),My_L,train_label,average_win)
test_pred=LRC.predict(test_data)
test_acc = np.sum(test_pred==test_label)/(1.0*len(test_pred))
print("Regularization_L:".format(),"Test Accuracy is".format(),My_L,test_acc)

(0, ' th sample')
(100, ' th sample')
(200, ' th sample')
(300, ' th sample')
(400, ' th sample')
(500, ' th sample')
(600, ' th sample')
(700, ' th sample')
(800, ' th sample')
(900, ' th sample')
(1000, ' th sample')
(1100, ' th sample')
('Regularization_L:', 'Test Accuracy is', 13, 0.7)
